# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Pipeline

on:
  push:
    branches: [master]

env:
  RUN_ID: ${{ github.run_id }}
  RH_USERNAME: ${{ secrets.RH_USERNAME }}
  RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
  RH_2FA: ${{ secrets.RH_2FA }}
  IEXCLOUD: ${{ secrets.IEXCLOUD_SANDBOX }}
  STOCKTWITS: ${{ secrets.STOCKTWITS }}
  GLASSNODE: ${{ secrets.GLASSNODE }}
  BLS: ${{ secrets.BLS }}
  POLYGON: ${{ secrets.POLYGON }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v2.1.5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run all unit tests
        env:
          S3_BUCKET: ${{ secrets.S3_DEV_BUCKET }}
        run: coverage run -m pytest -vv

      - name: Generate test coverage report
        run: coverage report -m --fail-under=90

      - name: Upload repo to S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: python scripts/update_repo.py
